name: apod
description: Astronomy Picture of the Day

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  cached_network_image: ^3.1.0+1
  chopper: ^4.0.3
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  freezed_annotation: ^0.15.0
  go_router: ^2.2.1
  google_fonts: ^2.1.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  json_annotation: ^4.3.0
  logging: ^1.0.2
  provider: ^6.0.1
  uuid: ^3.0.5

dev_dependencies:
  build_runner: ^2.1.5
  chopper_generator: ^4.0.3
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^0.15.1+1
  json_serializable: ^6.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
